// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $animated_link from "./routes/animated_link.tsx";
import * as $animated_list from "./routes/animated_list.tsx";
import * as $buffer_loading from "./routes/buffer_loading.tsx";
import * as $index from "./routes/index.tsx";
import * as $tag_search from "./routes/tag_search.tsx";
import * as $AnimatedList from "./islands/AnimatedList.tsx";
import * as $SuggestedSearchbar from "./islands/SuggestedSearchbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/animated_link.tsx": $animated_link,
    "./routes/animated_list.tsx": $animated_list,
    "./routes/buffer_loading.tsx": $buffer_loading,
    "./routes/index.tsx": $index,
    "./routes/tag_search.tsx": $tag_search,
  },
  islands: {
    "./islands/AnimatedList.tsx": $AnimatedList,
    "./islands/SuggestedSearchbar.tsx": $SuggestedSearchbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
