// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $animated_border from "./routes/animated_border.tsx";
import * as $animated_link from "./routes/animated_link.tsx";
import * as $animated_list from "./routes/animated_list.tsx";
import * as $buffer_loading from "./routes/buffer_loading.tsx";
import * as $circle_animation from "./routes/circle_animation.tsx";
import * as $home from "./routes/home.tsx";
import * as $image_card_flip from "./routes/image_card_flip.tsx";
import * as $index from "./routes/index.tsx";
import * as $tag_search from "./routes/tag_search.tsx";
import * as $AnimatedBorder from "./islands/AnimatedBorder.tsx";
import * as $AnimatedList from "./islands/AnimatedList.tsx";
import * as $SuggestedSearchbar from "./islands/SuggestedSearchbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/animated_border.tsx": $animated_border,
    "./routes/animated_link.tsx": $animated_link,
    "./routes/animated_list.tsx": $animated_list,
    "./routes/buffer_loading.tsx": $buffer_loading,
    "./routes/circle_animation.tsx": $circle_animation,
    "./routes/home.tsx": $home,
    "./routes/image_card_flip.tsx": $image_card_flip,
    "./routes/index.tsx": $index,
    "./routes/tag_search.tsx": $tag_search,
  },
  islands: {
    "./islands/AnimatedBorder.tsx": $AnimatedBorder,
    "./islands/AnimatedList.tsx": $AnimatedList,
    "./islands/SuggestedSearchbar.tsx": $SuggestedSearchbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
